env: ${ENV}

server:
  port: 8080

spring:
  application:
    name: car-market
  sleuth:
    sampler:
      probability: 1.0
  liquibase:
    change-log: classpath:/liquibase/master.xml
    enabled: ${LBENABLE}
    databaseChangeLogTable: databasechangelog
    databaseChangeLogLockTable: databasechangeloglock

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name : org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
